// Barrel file for page components
export { HomePage } from './HomePage';
export { WebPage } from './WebPage';
export { ThreePage } from './ThreePage';
export { TeachingPage } from './TeachingPage';
export { ContactPage } from './ContactPage';
export { ShopPage } from './ShopPage';
export { UpdatesPage } from './UpdatesPage';
export { ProjectDetailPage } from './ProjectDetailPage';
export { UpdateDetailPage } from './UpdateDetailPage';
export { AboutPage } from './AboutPage';
export { NotFoundPage } from './NotFoundPage';
