export function getCoursesCopy(locale: 'da' | 'en') {
  return {
    da: {
      filterTitle: 'Filtrér forløb',
      filterSubjectLabel: 'Søg på ord',
      filterSubjectPlaceholder: 'Skriv et emne, tema eller ord',
      filterTargetLabel: 'Målgruppe',
      filterAllTargets: 'Alle målgrupper',
      filterTargetIndskoling: 'Indskoling',
      filterTargetMellemtrin: 'Mellemtrin',
      filterTargetUdskoling: 'Udskoling',
      filterTargetGymnasium: 'Gymnasium',
      filterReset: 'Ryd filter',
      filterTracksResult: 'forløb',
      filterFocusResult: 'fokuskurser',
      filterNoResults: 'Ingen forløb matcher det valgte filter.',
      filterTargetOnlyHint: 'Vi viser kun filtrering på målgrupper, så du hurtigt kan vælge det rigtige klassetrin.',
      customTrackTitle: 'Mit eget forløb',
      customTrackText: 'Få et skræddersyet forløb til jeres mål, klassetrin, tid og lokale rammer.',
      customTrackButton: 'Book skræddersyet forløb',
      bookingButton: 'Book forløb',
      bookingOpenCartButton: 'Åbn booking i ny fane',
      modalTitle: 'Book forløb og kurser',
      modalIntro: 'Vælg de ønskede forløb/kurser og angiv antal.',
      modalSelectionLabel: 'Valgte tilbud',
      modalSelectionHint: 'Du kan vælge flere tilbud og justere antal direkte her.',
      modalContactLabel: 'Kontaktoplysninger',
      bookingSummaryCountUnit: 'valg',
      sectionTitle: 'Valg og antal',
      sectionEmpty: 'Vælg mindst ét tilbud i listen nedenfor.',
      quantityLabel: 'Antal hold/klasser',
      kindTrack: 'Forløb',
      kindFocus: 'Fokuskursus',
      removeSelection: 'Fjern',
      nameLabel: 'Navn',
      schoolLabel: 'Skole',
      eanLabel: 'EAN-nummer (valgfrit)',
      eanPlaceholder: 'Fx 5798000000000',
      emailLabel: 'Email',
      studentsLabel: 'Antal elever',
      studentsPlaceholder: 'Fx 24',
      classesLabel: 'Antal klasser/hold',
      classesPlaceholder: 'Fx 1',
      messageLabel: 'Kommentar',
      messagePlaceholder: 'Skriv gerne klassetrin, ønsket periode og særlige ønsker.',
      submitLabel: 'Send bookingforespørgsel',
      submitSendingLabel: 'Sender...',
      closeLabel: 'Luk',
      selectError: 'Vælg mindst ét forløb eller kursus.',
      sendError: 'Kunne ikke sende bookingforespørgslen. Prøv igen om et øjeblik.',
      configError: 'Email er ikke sat korrekt op endnu. Kontakt administrator.',
      sendSuccess: 'Tak! Din bookingforespørgsel er sendt.',
      sendSuccessNoAutoReply: 'Bookingforespørgslen er sendt til NordPixel, men autosvar til kunden er ikke konfigureret endnu.',
      cartPageTitle: 'Bookingkurv',
      cartPageIntro: 'Vælg forløb, antal og kontaktoplysninger.',
      cartPageReminder1: 'EAN er valgfri.',
      cartPageReminder2: '',
      cartPageReminder3: '',
      cartCatalogTitle: 'Vælg forløb og kurser',
      cartCatalogHint: 'Du kan markere flere elementer og sætte antal pr. element.',
      cartSummaryTopTitle: 'Valgt til booking',
      cartSummaryTopHint: 'Oversigt over dine nuværende valg',
      cartContactTitle: 'Kontaktoplysninger',
      phoneLabel: 'Telefon',
      phonePlaceholder: 'Fx 20 30 40 50',
      quantityIncrease: 'Øg antal',
      quantityDecrease: 'Sænk antal',
      cartBackToCourses: 'Tilbage til forløb',
      uvmIntroTitle: 'Klar løsning til teknologiforståelse',
      uvmIntroText:
        'Forløbene omsætter kravene i teknologiforståelse til konkret undervisning. Fokus er praktisk arbejde med digitale fænomener, kreativt design, programmering og kritisk undersøgelse.',
      teacherRoleLabel: 'Lærerens rolle',
      teacherRoleText:
        'Du er facilitator: rammesætter, støtter og hjælper eleverne med at omsætte idéer til konkrete produkter.',
      studentRoleLabel: 'Eleverne gør',
      studentRoleText:
        'Eleverne undersøger, bygger, tester og forbedrer. De lærer gennem eksperimenter, samarbejde og refleksion over teknologiens betydning.',
    },
    en: {
      filterTitle: 'Filter Programs',
      filterSubjectLabel: 'Search by word',
      filterSubjectPlaceholder: 'Search by topic, theme, or word',
      filterTargetLabel: 'Target Group',
      filterAllTargets: 'All target groups',
      filterTargetIndskoling: 'Lower primary',
      filterTargetMellemtrin: 'Middle grades',
      filterTargetUdskoling: 'Lower secondary',
      filterTargetGymnasium: 'Upper secondary',
      filterReset: 'Clear filter',
      filterTracksResult: 'programs',
      filterFocusResult: 'focus courses',
      filterNoResults: 'No programs match the selected filter.',
      filterTargetOnlyHint: 'Filtering is currently based on target group, so you can quickly select the right grade level.',
      customTrackTitle: 'Custom Program',
      customTrackText: 'Get a tailored program aligned with your goals, grade level, schedule, and local context.',
      customTrackButton: 'Request a tailored program',
      bookingButton: 'Add to Booking',
      bookingOpenCartButton: 'Open Booking Cart',
      modalTitle: 'Book Programs and Courses',
      modalIntro: 'Select the relevant programs or courses and set quantities.',
      modalSelectionLabel: 'Selected items',
      modalSelectionHint: 'You can choose multiple items and adjust quantities here.',
      modalContactLabel: 'Contact Information',
      bookingSummaryCountUnit: 'selections',
      sectionTitle: 'Selection and Quantity',
      sectionEmpty: 'Select at least one item below.',
      quantityLabel: 'Number of groups/classes',
      kindTrack: 'Program',
      kindFocus: 'Focus course',
      removeSelection: 'Remove',
      nameLabel: 'Name',
      schoolLabel: 'School',
      eanLabel: 'EAN number (optional)',
      eanPlaceholder: 'For example 5798000000000',
      emailLabel: 'Email',
      studentsLabel: 'Number of students',
      studentsPlaceholder: 'For example 24',
      classesLabel: 'Number of classes/groups',
      classesPlaceholder: 'For example 1',
      messageLabel: 'Notes',
      messagePlaceholder: 'Share grade level, preferred timing, and special requests.',
      submitLabel: 'Send booking request',
      submitSendingLabel: 'Sending...',
      closeLabel: 'Close',
      selectError: 'Select at least one program or course.',
      sendError: 'Could not send the booking request. Please try again shortly.',
      configError: 'Email is not configured yet. Please contact the site administrator.',
      sendSuccess: 'Thanks! Your booking request has been sent.',
      sendSuccessNoAutoReply: 'The booking request was sent to NordPixel, but customer auto-reply is not configured yet.',
      cartPageTitle: 'Booking Cart',
      cartPageIntro: 'Select items, quantities, and your contact details.',
      cartPageReminder1: 'EAN is optional.',
      cartPageReminder2: '',
      cartPageReminder3: '',
      cartCatalogTitle: 'Select programs and courses',
      cartCatalogHint: 'You can select multiple items and set a quantity for each item.',
      cartSummaryTopTitle: 'Current booking overview',
      cartSummaryTopHint: 'A quick overview of your selected items',
      cartContactTitle: 'Contact details',
      phoneLabel: 'Phone',
      phonePlaceholder: 'For example +45 20 30 40 50',
      quantityIncrease: 'Increase quantity',
      quantityDecrease: 'Decrease quantity',
      cartBackToCourses: 'Back to courses',
      uvmIntroTitle: 'Classroom-ready technology literacy solution',
      uvmIntroText:
        'These programs translate technology literacy requirements into practical classroom delivery. The focus is on digital phenomena, creative design, coding, and critical inquiry.',
      teacherRoleLabel: 'Teacher role',
      teacherRoleText:
        'You facilitate by framing the work, supporting students, and helping them turn ideas into concrete outcomes.',
      studentRoleLabel: 'Students do',
      studentRoleText:
        'Students investigate, build, test, and improve. They learn through experimentation, collaboration, and reflection on the impact of technology.',
    },
  }[locale];
}
