export function getCoursesCopy(locale: 'da' | 'en') {
  return {
    da: {
      filterTitle: 'Filtrér forløb',
      filterSubjectLabel: 'Søg på ord',
      filterSubjectPlaceholder: 'Skriv et emne, tema eller ord',
      filterTargetLabel: 'Målgruppe',
      filterAllTargets: 'Alle målgrupper',
      filterTargetIndskoling: 'Indskoling',
      filterTargetMellemtrin: 'Mellemtrin',
      filterTargetUdskoling: 'Udskoling',
      filterTargetGymnasium: 'Gymnasium',
      filterReset: 'Ryd filter',
      filterTracksResult: 'forløb',
      filterFocusResult: 'fokuskurser',
      filterNoResults: 'Ingen forløb matcher det valgte filter.',
      bookingButton: 'Book forløb',
      bookingOpenCartButton: 'Åbn booking i ny fane',
      modalTitle: 'Book forløb og kurser',
      modalIntro: 'Vælg de ønskede forløb/kurser og angiv antal.',
      modalSelectionLabel: 'Valgte tilbud',
      modalSelectionHint: 'Du kan vælge flere tilbud og justere antal direkte her.',
      modalContactLabel: 'Kontaktoplysninger',
      bookingSummaryCountUnit: 'valg',
      sectionTitle: 'Valg og antal',
      sectionEmpty: 'Vælg mindst ét tilbud i listen nedenfor.',
      quantityLabel: 'Antal',
      kindTrack: 'Forløb',
      kindFocus: 'Fokuskursus',
      removeSelection: 'Fjern',
      nameLabel: 'Navn',
      schoolLabel: 'Skole',
      emailLabel: 'Email',
      messageLabel: 'Kommentar',
      messagePlaceholder: 'Skriv gerne klassetrin, ønsket periode og særlige ønsker.',
      submitLabel: 'Send bookingforespørgsel',
      submitSendingLabel: 'Sender...',
      closeLabel: 'Luk',
      selectError: 'Vælg mindst ét forløb eller kursus.',
      sendError: 'Kunne ikke sende bookingforespørgslen. Prøv igen om et øjeblik.',
      configError: 'Email er ikke sat korrekt op endnu. Kontakt administrator.',
      sendSuccess: 'Tak! Din bookingforespørgsel er sendt.',
      sendSuccessNoAutoReply: 'Bookingforespørgslen er sendt til NordPixel, men autosvar til kunden er ikke konfigureret endnu.',
      cartPageTitle: 'Bookingkurv',
      cartPageIntro: 'Vælg forløb og fokuskurser, justér antal, og udfyld kontaktoplysninger.',
      cartPageReminder1: 'Her booker du de elementer, I vil arbejde med i klassen.',
      cartPageReminder2: 'Vi bruger oplysningerne til at planlægge forløb, tid og materialer sammen med jer.',
      cartCatalogTitle: 'Vælg forløb og kurser',
      cartCatalogHint: 'Du kan markere flere elementer og sætte antal pr. element.',
      cartContactTitle: 'Kontaktoplysninger',
      phoneLabel: 'Telefon',
      phonePlaceholder: 'Fx 20 30 40 50',
      quantityIncrease: 'Øg antal',
      quantityDecrease: 'Sænk antal',
      cartBackToCourses: 'Tilbage til forløb',
    },
    en: {
      filterTitle: 'Filter Tracks',
      filterSubjectLabel: 'Search by word',
      filterSubjectPlaceholder: 'Search by topic, theme, or word',
      filterTargetLabel: 'Target group',
      filterAllTargets: 'All target groups',
      filterTargetIndskoling: 'Lower primary',
      filterTargetMellemtrin: 'Middle grades',
      filterTargetUdskoling: 'Upper secondary',
      filterTargetGymnasium: 'Gymnasium',
      filterReset: 'Clear filter',
      filterTracksResult: 'tracks',
      filterFocusResult: 'focus courses',
      filterNoResults: 'No tracks match the selected filter.',
      bookingButton: 'Book Track',
      bookingOpenCartButton: 'Open booking in new tab',
      modalTitle: 'Book Tracks and Courses',
      modalIntro: 'Choose the requested tracks/courses and set quantities.',
      modalSelectionLabel: 'Selected items',
      modalSelectionHint: 'You can choose multiple items and adjust quantities here.',
      modalContactLabel: 'Contact information',
      bookingSummaryCountUnit: 'selections',
      sectionTitle: 'Selection and quantity',
      sectionEmpty: 'Select at least one item below.',
      quantityLabel: 'Quantity',
      kindTrack: 'Track',
      kindFocus: 'Focus Course',
      removeSelection: 'Remove',
      nameLabel: 'Name',
      schoolLabel: 'School',
      emailLabel: 'Email',
      messageLabel: 'Notes',
      messagePlaceholder: 'Share grade level, preferred timing, and special requests.',
      submitLabel: 'Send Booking Request',
      submitSendingLabel: 'Sending...',
      closeLabel: 'Close',
      selectError: 'Select at least one track or course.',
      sendError: 'Could not send the booking request. Please try again shortly.',
      configError: 'Email is not configured yet. Please contact the site administrator.',
      sendSuccess: 'Thanks! Your booking request has been sent.',
      sendSuccessNoAutoReply: 'The booking request was sent to NordPixel, but customer auto-reply is not configured yet.',
      cartPageTitle: 'Booking Cart',
      cartPageIntro: 'Choose tracks and focus courses, adjust quantities, and fill in contact details.',
      cartPageReminder1: 'Use this page to choose exactly what your class wants to book.',
      cartPageReminder2: 'We use your details to plan scope, timing, and materials together with your school.',
      cartCatalogTitle: 'Select tracks and courses',
      cartCatalogHint: 'You can select multiple items and set quantity per item.',
      cartContactTitle: 'Contact details',
      phoneLabel: 'Phone',
      phonePlaceholder: 'For example +45 20 30 40 50',
      quantityIncrease: 'Increase quantity',
      quantityDecrease: 'Decrease quantity',
      cartBackToCourses: 'Back to courses',
    },
  }[locale];
}
